Bug:

  Traceback (most recent call last):
    File "maliv2.py", line 177, in <module>
      new_conflict_zones += conflict_zones[i]
  TypeError: 'Location' object is not iterable

Solution:

  change:
    list_of_locations += new_location
  to:
    list_of_locations += [new_location]

